// flow-typed signature: 8537d13f46eabb1fb57eda16f3bc5472
// flow-typed version: <<STUB>>/decompress_v4.2.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decompress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decompress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'decompress/index' {
  declare module.exports: $Exports<'decompress'>;
}
declare module 'decompress/index.js' {
  declare module.exports: $Exports<'decompress'>;
}
