// flow-typed signature: 3477c67f893cbfe81c14fb806dd6d40b
// flow-typed version: <<STUB>>/dir-compare_v1.7.2/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dir-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dir-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dir-compare/common' {
  declare module.exports: any;
}

declare module 'dir-compare/compareAsync' {
  declare module.exports: any;
}

declare module 'dir-compare/compareSync' {
  declare module.exports: any;
}

declare module 'dir-compare/defaultResultBuilderCallback' {
  declare module.exports: any;
}

declare module 'dir-compare/dircompare' {
  declare module.exports: any;
}

declare module 'dir-compare/file_compare_handlers/bufferPool' {
  declare module.exports: any;
}

declare module 'dir-compare/file_compare_handlers/common' {
  declare module.exports: any;
}

declare module 'dir-compare/file_compare_handlers/defaultFileCompare' {
  declare module.exports: any;
}

declare module 'dir-compare/file_compare_handlers/fileDescriptorQueue' {
  declare module.exports: any;
}

declare module 'dir-compare/file_compare_handlers/lineBasedFileCompare' {
  declare module.exports: any;
}

declare module 'dir-compare/file_compare_handlers/queue' {
  declare module.exports: any;
}

declare module 'dir-compare/print' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/extract' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/manual/test-compare' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/manual/test-concurrent' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/manual/test-leaks' {
  declare module.exports: any;
}

declare module 'dir-compare/tests/untar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dir-compare/common.js' {
  declare module.exports: $Exports<'dir-compare/common'>;
}
declare module 'dir-compare/compareAsync.js' {
  declare module.exports: $Exports<'dir-compare/compareAsync'>;
}
declare module 'dir-compare/compareSync.js' {
  declare module.exports: $Exports<'dir-compare/compareSync'>;
}
declare module 'dir-compare/defaultResultBuilderCallback.js' {
  declare module.exports: $Exports<'dir-compare/defaultResultBuilderCallback'>;
}
declare module 'dir-compare/dircompare.js' {
  declare module.exports: $Exports<'dir-compare/dircompare'>;
}
declare module 'dir-compare/file_compare_handlers/bufferPool.js' {
  declare module.exports: $Exports<'dir-compare/file_compare_handlers/bufferPool'>;
}
declare module 'dir-compare/file_compare_handlers/common.js' {
  declare module.exports: $Exports<'dir-compare/file_compare_handlers/common'>;
}
declare module 'dir-compare/file_compare_handlers/defaultFileCompare.js' {
  declare module.exports: $Exports<'dir-compare/file_compare_handlers/defaultFileCompare'>;
}
declare module 'dir-compare/file_compare_handlers/fileDescriptorQueue.js' {
  declare module.exports: $Exports<'dir-compare/file_compare_handlers/fileDescriptorQueue'>;
}
declare module 'dir-compare/file_compare_handlers/lineBasedFileCompare.js' {
  declare module.exports: $Exports<'dir-compare/file_compare_handlers/lineBasedFileCompare'>;
}
declare module 'dir-compare/file_compare_handlers/queue.js' {
  declare module.exports: $Exports<'dir-compare/file_compare_handlers/queue'>;
}
declare module 'dir-compare/index' {
  declare module.exports: $Exports<'dir-compare'>;
}
declare module 'dir-compare/index.js' {
  declare module.exports: $Exports<'dir-compare'>;
}
declare module 'dir-compare/print.js' {
  declare module.exports: $Exports<'dir-compare/print'>;
}
declare module 'dir-compare/tests/extract.js' {
  declare module.exports: $Exports<'dir-compare/tests/extract'>;
}
declare module 'dir-compare/tests/manual/test-compare.js' {
  declare module.exports: $Exports<'dir-compare/tests/manual/test-compare'>;
}
declare module 'dir-compare/tests/manual/test-concurrent.js' {
  declare module.exports: $Exports<'dir-compare/tests/manual/test-concurrent'>;
}
declare module 'dir-compare/tests/manual/test-leaks.js' {
  declare module.exports: $Exports<'dir-compare/tests/manual/test-leaks'>;
}
declare module 'dir-compare/tests/untar.js' {
  declare module.exports: $Exports<'dir-compare/tests/untar'>;
}
