// flow-typed signature: 63385b083be432417b845260cff51ada
// flow-typed version: <<STUB>>/rollup-plugin-executable_v1.4.5/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-executable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-executable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-executable/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-executable/lib/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-executable/lib/index.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-executable/lib/index.cjs'>;
}
declare module 'rollup-plugin-executable/lib/index.esm.js' {
  declare module.exports: $Exports<'rollup-plugin-executable/lib/index.esm'>;
}
