// @flow

export type GitHubAsset = {|
  id: number,
  label: string,
  name: string,
  node_id: string,
  url: string,
  browser_download_url: string,
  content_type: string,
  created_at: string,
  download_count: number,
  size: number,
  state: string,
  updated_at: string,
  uploader: {
    avatar_url: string,
    events_url: string,
    followers_url: string,
    following_url: string,
    gists_url: string,
    gravatar_id: string,
    html_url: string,
    id: number,
    login: string,
    node_id: string,
    organizations_url: string,
    received_events_url: string,
    repos_url: string,
    site_admin: false,
    starred_url: string,
    subscriptions_url: string,
    type: string,
    url: string,
  },
|};
