// @flow

import type { GitHubAsset } from './GitHubAsset';

export type GitHubRelease = {|
  assets: GitHubAsset[],
  assets_url: string,
  author: {
    login: string,
    id: number,
    node_id: string,
    avatar_url: string,
    gravatar_id: string,
    url: string,
    html_url: string,
    followers_url: string,
    following_url: string,
    gists_url: string,
    starred_url: string,
    subscriptions_url: string,
    organizations_url: string,
    repos_url: string,
    events_url: string,
    received_events_url: string,
    type: string,
    site_admin: false,
  },
  body: string,
  created_at: string,
  draft: boolean,
  html_url: string,
  id: number,
  name: string,
  node_id: string,
  prerelease: boolean,
  published_at: string,
  tag_name: string,
  tarball_url: string,
  target_commitish: string,
  upload_url: string,
  url: string,
  zipball_url: string,
|};
